Feature/#7 create login system
ts1982/laravel-todo pull request #8
Opened 2022-10-05 09:14 UTC by ts1982

基本的なログインシステムの実装が完了しました。

ログイン時、会員登録時のアラート日本語化はまだできておりません。
また、パスワード再発行機能もこれから追加予定です。

FolderControllerのshowメソッドのロジックが個人的にはあまり上手くないと思っているので、アドバイスございましたらよろしくお願いいたします。

ご確認よろしくお願いいたします。

2022-10-05 09:45 UTC, YutaInouePH requested changes

2022-10-05 09:45 UTC, YutaInouePH commented on src/routes/web.php
> +    Route::delete('/{folder}/delete', [FolderController::class, 'delete'])->name('delete')->middleware('auth');
middleware は group() 関数でまとめることが可能
`group(['prefix' => 'folders', 'as' => 'folders.', 'middleware' => 'auth'], function () {})`

2022-10-05 09:54 UTC, ts1982 commented on src/app/Http/Controllers/FolderController.php
> +        $tasks = '';
その場合、URLを変更すると他のユーザーのタスクが見れてしまうと思うのですが、いかがでしょうか？

2022-10-05 10:02 UTC, ts1982 commented on src/app/Http/Controllers/FolderController.php
> +        $tasks = '';
その直下の

`        if ($folders->contains('id', $folder->id)) {
            $tasks = Task::where('folder_id', $folder->id)->get();
        }`

この部分は必要でしょうか。もしくはもっと良い記述方法がありそうでしょうか？

2022-10-06 16:16 UTC, YutaInouePH requested changes

2022-10-06 16:16 UTC, YutaInouePH commented on src/resources/views/auth/login.blade.php
> +                                {{-- <input type="hidden" name="_token" value="LDRHeyJYemuzXpLylyuRRH0L3vbhLBJzqf3NNMYZ"> --}}
これは消しても良い

2022-10-06 16:16 UTC, YutaInouePH commented on src/resources/views/auth/login.blade.php
> +                        <a href="http://intern-3.stg.commude.biz/password/reset">パスワードの変更はこちらから</a>
href属性を修正

2022-10-06 16:16 UTC, YutaInouePH commented on src/resources/views/components/header.blade.php
> +                    {{-- <input type="hidden" name="_token" value="LDmFpir3LMnHmCLbjpI6ffaNDtM5ev1ag2ys3hVF"> --}}
削除する

2022-10-06 16:16 UTC, YutaInouePH commented on src/resources/views/components/header.blade.php
> +                <a href="https://intern-3.stg.commude.biz/folders/create#" id="logout" class="my-navbar-item">ログアウト</a>
href属性の修正

2022-10-07 02:47 UTC, ts1982 commented on src/resources/views/components/header.blade.php
> +                <a href="https://intern-3.stg.commude.biz/folders/create#" id="logout" class="my-navbar-item">ログアウト</a>
こちら修正しましたが、あまり自信がないです。

2022-10-07 02:58 UTC, YutaInouePH approved these changes

2022-10-07 03:19 UTC, merged